Repository openshift-pipelines/task-maven, pull requests merged in 2024-03, with the labels that each got.

#18 CI: fix kubernetes repository
  ci/ci.Dockerfile
  ci/kubernetes.repo
Labels: approved

#17 Add target for removing created resources
  Makefile
Labels: approved, lgtm, ok-to-test

#21 Release Prep
  .gitignore
  Chart.yaml
  Makefile
  hack/release.sh
  test/e2e/e2e.bats
  test/e2e/resources/pipeline-maven.yaml
Labels: approved, lgtm
